version: "2"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file: .env
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - code-network
  web:
    image: nginx:mainline-alpine-perl
    depends_on:
      - mysql
      - php
    ports:
      - "8080:80"
    networks:
      - code-network
    volumes:
      - ./nginx-conf/site.conf:/etc/nginx/conf.d/site.conf
  php:
    image: php:7-fpm
    depends_on:
      - mysql
    volumes:
      - ./app:/code
    networks:
      - code-network

networks:
  code-network:
    driver: bridge
volumes:
  db-data: